# Generated by Django 3.2.8 on 2021-10-13 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FORUMAPP', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='iForum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posts', models.TextField()),
            ],
        ),
    ]
