# Generated by Django 3.2.8 on 2021-10-13 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FORUMAPP', '0002_iforum'),
    ]

    operations = [
        migrations.AddField(
            model_name='iforum',
            name='pc',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
