# Generated by Django 3.2.8 on 2021-10-13 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FORUMAPP', '0003_iforum_pc'),
    ]

    operations = [
        migrations.AddField(
            model_name='iforum',
            name='username',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
