# Generated by Django 3.2.8 on 2021-10-14 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FORUMAPP', '0004_iforum_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('comments', models.CharField(max_length=100)),
                ('likes', models.IntegerField(default=0)),
            ],
        ),
    ]
