# Generated by Django 3.2.8 on 2021-10-15 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FORUMAPP', '0005_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.AddField(
            model_name='iforum',
            name='comments',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='iforum',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
